# Dependencies
markdown:         redcarpet
highlight:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ihsan Ariswanto
tagline:          'blog pribadi'
description:      'Blog ini adalah kelanjutan dari blog sebelumnya <a href="http://www.ariswanto.web.id/arsip/index.html">(2010-2015)</a> yang sekarang sudah diarsipkan.'
url:              http://www.ariswanto.web.id

author:
  name:           'Ihsan Ariswanto'
  url:            https://twitter.com/IhsanAriswanto

paginate:         5

# Custom vars
#version:          15.09

#github:
#  repo:           https://github.com/ariswanto/ariswanto.github.io
